### ISSUE TITLE
FPort on swaped TX/RX uart dont work

### ISSUE THREAD

**Issue by r1000ru** [ArduCustom/ardupilot#206]
## Bug report

**Issue details**

Standart (inverted) FPORT out from R9 to SERIAL7 TX (Options are set: InvertTX, InvertRX, HalfDuplex) - all work.
Standart (inverted) FPORT out from R9 to SERIAL7 RX (Options are set: InvertTX, InvertRX, HalfDuplex, Swap TX/RX) - Failsafe.
Swaping is work on standart Ardupilot 4.2 airplane.

**Version**
ArduCustom Airplane V10.0 (Full)

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[*] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Classic airplane

**Hardware type**
Matek H743-Wing V1
R9 Slim OTA

**Comment by shellixyz** [comment]
That's really odd because there is no change in related parts (serial ports and FPort) in Custom V10. They must have broken it upstream in master recently.

**Comment by shellixyz** [comment]
@r1000ru Could you please check with V11.0 dev whether the issue has been fixed
[MatekH743_plane_bin_custom-v11.0-dev_69422b8cb5.zip](https://github.com/ArduCustom/ardupilot/files/9394734/MatekH743_plane_bin_custom-v11.0-dev_69422b8cb5.zip)
