### ISSUE TITLE
Target request: SpeedyBee F405 Wing

### ISSUE THREAD

**Issue by Target0815** [ArduCustom/ardupilot#235]
Can you add this board? [SpeedyBee F405 Wing](https://www.speedybee.com/speedybee-f405-wing-app-fixed-wing-flight-controller/)

**Comment by shellixyz** [comment]
Yes it will be in the next release which will happen soon hopefully

**Comment by Target0815** [comment]
Is there any news about the FC yet?

**Comment by mf0o** [comment]
I did compile ArduCustom-Arduplane (with the target from official) a while ago for the Speedybee and its running on several planes & pilots without any issues.
You can get it here for now: https://drive.google.com/file/d/1oN7TE4hSoZWxb3qUy_z6A6dy_PNwNUkv/view?usp=drive_link

**Comment by Target0815** [comment]
@mf0o Which Arduplane version is this based on?

**Comment by mf0o** [comment]
Its ArduCustom v11.1 (https://github.com/ArduCustom/ardupilot/releases/tag/custom-v11.1) which is based on official ArduPilot v4.4.0dev from October 17th 2022, with one minor addition to widen the OSD sidebars via OSD_OPTIONS += 131072

**Comment by Target0815** [comment]
Is there already a new release based on Arduplane 4.4.x?

**Comment by shellixyz** [comment]
Not yet, I couldn't find time to work on it  unfortunately

**Comment by shellixyz** [comment]
This target is going to be part of the V11.2 release which is going to come out very soon
